### PR TITLE
docker user

### PR DESCRIPTION
**Pull request by gambol99**
- shifting the version to v1.2.1
- adding a user in the docker file to ensure we dont run as root

### CODE REVIEW

**Comment by gambol99** [comment]
fixes issue https://github.com/gambol99/keycloak-proxy/issues/88

**Comment by gambol99** [comment]
@timgent?

**Comment by timgent** [comment]
Thanks!

**Comment by nabadger** [comment]
@gambol99 

Hi - it looks like this isn't on current master anymore - did it get removed for any reason?

I can see it was removed in #107 

We have a policy on our k8s cluster that doesn't allow containers to run as root (so I'd have to build my own container to use this). 

I'm not sure there's a good reason to run any container as root these days - there always tends to be available workarounds right?

Thanks

**Comment by jangaraj** [comment]
@nabadger I guess, you can use [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/):
```
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
```

**Pull request merged**
